MVC_Simple_DB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Simple_DB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listing()
        {
            ViewBag.Message = "List of requested maintenence";

            return View();
        }

    }
}

MVC_Simple_DB/Controllers/ReqFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Simple_DB.Controllers
{
    public class ReqFormController : Controller
    {
        // GET: Req
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC_Simple_DB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Maintenence Request Example</h1>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Request Submition</h2>
        <p>
            Submit a request for maintenence.
        </p>
        <p>@Html.ActionLink(HttpUtility.HtmlDecode("Click here! &raquo;"), "Index", "ReqForm", new { @class = "elements" }, null)</p>
    </div>
    <div class="col-md-6">
        <h2>Request Listing</h2>
        <p>
            View the requested maintenence.
        </p>
        <p>@Html.ActionLink(HttpUtility.HtmlDecode("Click here! &raquo;"), "Listing", "Home", new { @class = "elements" })</p>
    </div>
</div>

MVC_Simple_DB/Views/Home/Listing.cshtml
@{
    ViewBag.Title = "Request List";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC_Simple_DB/Views/ReqForm/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MVC_Simple_DB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Maintenence Request Example</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Request Submition", "Index", "ReqForm", new { @class = "elements" }, null)</li>
                    <li>@Html.ActionLink("Request List", "Listing", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>